// <auto-generated />
using System;
using ItCollabora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ItCollabora.Migrations
{
    [DbContext(typeof(SystemOfUserDBContext))]
    [Migration("20231007192938_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ItCollabora.Models.RentModel", b =>
                {
                    b.Property<Guid>("RentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RentId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Rent");
                });

            modelBuilder.Entity("ItCollabora.Models.RoomModel", b =>
                {
                    b.Property<Guid>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("RentedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserModelUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RoomId");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("RentedByUserId");

                    b.HasIndex("UserModelUserId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("ItCollabora.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ItCollabora.Models.RentModel", b =>
                {
                    b.HasOne("ItCollabora.Models.RoomModel", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ItCollabora.Models.UserModel", "User")
                        .WithMany("Rents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ItCollabora.Models.RoomModel", b =>
                {
                    b.HasOne("ItCollabora.Models.UserModel", "OwnerUser")
                        .WithMany("OwnedRooms")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItCollabora.Models.UserModel", "RentedByUser")
                        .WithMany("RentedRooms")
                        .HasForeignKey("RentedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItCollabora.Models.UserModel", "UserModelUser")
                        .WithMany()
                        .HasForeignKey("UserModelUserId");

                    b.Navigation("OwnerUser");

                    b.Navigation("RentedByUser");

                    b.Navigation("UserModelUser");
                });

            modelBuilder.Entity("ItCollabora.Models.UserModel", b =>
                {
                    b.Navigation("OwnedRooms");

                    b.Navigation("RentedRooms");

                    b.Navigation("Rents");
                });
#pragma warning restore 612, 618
        }
    }
}
